### ISSUE TITLE
[Bug Bounty] In the setting your asset distribution, blockNumber validation check error

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#10]
**Bug Description :**
start block, stop block number Error when compared.

**Path :**
main > community (click) > create your community (click) > get started (click)

**Case / Action / Input data :**
1. input start block = '5410882', input stop block = '6000000', click 'confirm add' button
![image](https://user-images.githubusercontent.com/37989388/131354846-5349c994-a5c6-4639-961a-97945992e12e.png)
2. saved success, click delete icon
![image](https://user-images.githubusercontent.com/37989388/131354953-9e6923d1-f1d3-4180-82e3-3e9939ad72ca.png)
3. delete success, input stop block = '6000000', click 'confirm add' button
![image](https://user-images.githubusercontent.com/37989388/131355157-0d9f1b65-a52a-4ae8-a87d-b2ebe197eb4c.png)
4. add error (tip noti)
![image](https://user-images.githubusercontent.com/37989388/131355200-f446ba20-ac13-45aa-83f1-bd7898fb324c.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Have fixed it

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
