### ISSUE TITLE
Contract invocation error

### ISSUE THREAD

**Issue by dukhanm16** [nutbox-dao/nutbox-interface-v2#108]
Hello sir 
      I'm Dukhan . When I was creating the pool then I found that transaction error is coming in which contract invocation error is being written in top right in the corner.Which you can see in the screenshot below.
    
![Screenshot_20220204-015548](https://user-images.githubusercontent.com/98985294/152427045-d79245ec-3af7-4b34-a035-e0216364bc2b.png)

 I request you to solve this problem as soon as possible.
                          Thank you ☺️

Trx address :- TMBGvmovpGSB1bF1WZeEXkSZbX8a1RCYJY

**Comment by terryyyyyy** [comment]
Check if you have at least 0.1 NUT in your wallet.
