### ISSUE TITLE
[Bug Bounty] Community Information Edit - Community Name Unlimited Inputs and Input Errors

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#11]
**Bug Description :**
Community Name And Community Link - Unlimited Inputs and Input Error.
Community Link - url validation not check

**Path :**
main > community (click) > Manage Your Community (click) > setting (click) > Community Information Edit (Click)

**Case / Action / Input data :**
1. input community name = 'Test Nutbox Community..' repeat
input community link = 'Url Link..' repeat
click 'Commit' button
![image](https://user-images.githubusercontent.com/37989388/131362362-0abaf0fc-376c-42f6-a422-93af960fc03d.png)
2. information popup
click 'Sign and...' Button
![image](https://user-images.githubusercontent.com/37989388/131362590-30dfe626-b77d-4393-bd67-ea2c473b50f7.png)
3. wallet sign popup
![image](https://user-images.githubusercontent.com/37989388/131362643-29a51563-0297-446e-ac9d-9d03d07ead55.png)
4. error
![image](https://user-images.githubusercontent.com/37989388/131362800-5b45cdb5-d92a-4be8-bb6f-da31662ef2fe.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Have done.
