### ISSUE TITLE
[Bug Bounty] Community Information - The alphabet 'e' or 'Hangul' is entered in the Community Balance/Community commision ratio input form.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#12]
**Bug Description :**
Community Balance/Community commision ratio - The alphabet 'e' or 'Hangul' is entered And It can be sent.
Commnuity Balance 'Confirm charge' Button - a typing error  AS-IS : 'Confirm charfe'

**Path :**
main > community (click) > Manage Your Community (click) > setting (click) > Community Information

**Case / Action / Input data :**
Case 1 : input Community Balance = '1e2' And Click 'Confirm charge' Button > wallet sign popup open
'Confirm charge' Button - a typing error  AS-IS : 'Confirm charfe'
![image](https://user-images.githubusercontent.com/37989388/131366373-4d3d01ec-b360-417b-bb6b-86b7b7993adf.png)
![image](https://user-images.githubusercontent.com/37989388/131367196-60a084e4-ca4f-4957-bdbf-cba39687f0a6.png)

Case 2 : input Community commision ratio = '1e' And Click 'Confirm charge' Button
![image](https://user-images.githubusercontent.com/37989388/131367525-d7a211e1-d16e-4d23-9b78-4ec67015deba.png)
![image](https://user-images.githubusercontent.com/37989388/131367510-aa12c6a3-fb8f-4fa8-b335-b0210a5aa7de.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
