### ISSUE TITLE
[Bug Bounty] First time connection - no default language is set.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#13]
**Bug Description :**
First time connection - no default language is set.
I think it's normal to set it in English instead of null.

**Path :**
main 

**Case / Action / Input data :**
![image](https://user-images.githubusercontent.com/37989388/131958466-5e5dbe20-e1d8-4062-a56e-628874874f16.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
