### ISSUE TITLE
[Bug Bounty] If you don't have a wallet or if you don't have a wallet connection, the page won't load normally.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#14]
**Bug Description :**
If you don't have a wallet or if you don't have a wallet connection, the page won't load normally.
Is this right?
The normal site displays the page normally and provides a wallet connetion button or guidance.
The same goes for Tronlink on Peanut Site.
That way, I can see how many people use it, how many communities there are.

**Path :**
main > Community
main > Crowdstaking
etc.

**Case / Action / Input data :**
case1 : 
![image](https://user-images.githubusercontent.com/37989388/131959422-9b9fecad-6777-4b18-aa2e-f3fa996ec6a1.png)
case2 : 
![image](https://user-images.githubusercontent.com/37989388/131959478-1e50ad9a-e950-4d3e-a140-fbee4a67275e.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
