### ISSUE TITLE
Settings icon error

### ISSUE THREAD

**Issue by sanu2002** [nutbox-dao/nutbox-interface-v2#154]
Site is slow and the settings button is disappear some time plz repair it,and overlay the site is excellent

**Comment by terryyyyyy** [comment]
#113 
Which setting button? What do you mean the button disappear?

**Comment by sanu2002** [comment]
Settings button in home disappear sometimes

**Comment by terryyyyyy** [comment]
That because the critical data is not fetching back.Without the data, we cant know which btn to show, so we hide it until the data back.
