### ISSUE TITLE
transaction hash not working

### ISSUE THREAD

**Issue by lkrdp** [nutbox-dao/nutbox-interface-v2#168]
block explorer transactions not showing

**Comment by alexbelij** [comment]
block explorer problem. what about this site?

**Comment by lkrdp** [comment]
chek all screenshots.. no transactions on block explorer

**Comment by alexbelij** [comment]
Again, this is a problem with the network or site where you are verifying the transaction. not [nutbox](https://nutbox.io/)
You check the transaction not on nutbox. right?

**Comment by alexbelij** [comment]
and there are no screenshots

**Comment by terryyyyyy** [comment]
There was some issues on moonbase.moonscan, and it has been fixed right now.
