### ISSUE TITLE
In moonbase explore transection not showing 

### ISSUE THREAD

**Issue by jaythu** [nutbox-dao/nutbox-interface-v2#177]
![Screenshot_2022-02-05-11-02-35-051_com kiwibrowser browser](https://user-images.githubusercontent.com/78494339/152630854-ff01f06c-ecb0-4332-82cf-c8540f9a5d16.jpg)
You can check screenshot

**Comment by alexbelij** [comment]
what does this problem have to do with the site?

**Comment by terryyyyyy** [comment]
#168
