### ISSUE TITLE
Functional errors.

### ISSUE THREAD

**Issue by sarthak62735** [nutbox-dao/nutbox-interface-v2#181]
This is a broad type of error that happens whenever software doesn't behave as intended. ...   When it comes to functionality, each program should work correctly, but sometimes it doesn’t and i feel same in nutbox platform.. When the software does not act as it is intended, this is a functionality error. and I found some functional error  which is usually found via functional testing by me... so plss look at your software and fix it asap..

**Comment by terryyyyyy** [comment]
What detail problems?
