### ISSUE TITLE
Space after comma

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#186]
No space after comma
https://test.nutbox.io/#/community/index
![image](https://user-images.githubusercontent.com/6646888/152631797-09ca8ab2-e80c-4201-b715-281bb29cd1d3.png)

**Comment by terryyyyyy** [comment]
What do you mean?

**Comment by alexbelij** [comment]
> What do you mean?

there is a space after the comma. your copywriter's omission.
as it is now:
`DeFi,social `

should be:
`DeFi, social `

**Comment by terryyyyyy** [comment]
Got it.
