### ISSUE TITLE
Nutbox

### ISSUE THREAD

**Issue by Dhillon1313** [nutbox-dao/nutbox-interface-v2#188]
In moonbase explore transection not showing
![Screenshot_2022-02-05-09-44-46-48_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/99067643/152632271-13655a76-89fc-45fc-8abe-249e0b97249e.jpg)

**Comment by alexbelij** [comment]
does not apply to this project

**Comment by terryyyyyy** [comment]
#168
