### ISSUE TITLE
Losing hover and active styles

### ISSUE THREAD

**Issue by triumphkrug** [nutbox-dao/nutbox-interface-v2#189]
1. Community "Enter" button no  :hover and :active styles.
https://test.nutbox.io/#/community/index
2. "+ Manage Community" button no  :hover and :active styles.
3. Profile link no  :hover and :active styles.
4. Manage community link no  :hover styles.
5. Links to communities in the sidebar no  :hover styles.
6. Сommunity directory link in sidebar no  :hover styles.
7. Link to social networks no  :hover styles.
8. Сommunity menu items no  :hover styles.
9. Rows clickable but no hover style (Community / member)
10. "+ Create proposal" button no  :hover styles.
11. "Commit" button no  :hover styles.
and others

example:
<img width="572" alt="Снимок экрана 2022-02-05 в 09 50 54" src="https://user-images.githubusercontent.com/6646888/152632003-dde90c35-b214-4f05-aee1-f6c003a3d1ce.png">
<img width="486" alt="Снимок экрана 2022-02-05 в 09 50 44" src="https://user-images.githubusercontent.com/6646888/152632005-fdcf8a57-e983-4283-bb17-8be52744fc43.png">

**Comment by terryyyyyy** [comment]
Fixed
