### ISSUE TITLE
bug or  Inadequate design

### ISSUE THREAD

**Issue by linmumu16504941** [nutbox-dao/nutbox-interface-v2#2]
When staking mining, only the coins deployed at creation time can be pledged, but BNB cannot be pledged, and the contract that requires pledged coins cannot be seen in the direct interface. So how to pledge, it seems that only the owner of the deployment can see Own token contract

**Comment by linmumu16504941** [comment]
Maybe increase the option of whether to display the contract publicly or hide the contract when deploying tokens?

**Comment by terryyyyyy** [comment]
And we will provide some commen token for you.You can see them in asset droplist.

**Comment by IreneZ5** [comment]
# @linmumu16504941 Hi,Could you please provide your Tron  Address?
https://blog.nutbox.io/@nutbox/nutbox-walnut-bug-bounty-program
