### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by abahsheza** [nutbox-dao/nutbox-interface-v2#20]
On the Issue page of GitHub, fill in the bug information as shown in the figure below. Usually, it is needed to provide the phenomenon of the bug and the steps to reproduce the bug. If it is a security related issue, please contact the Nutbox official members directly instead of recording it here.
Finally, don't forget to write down your Tron address.
TKnYLrzM2dxwjuV2XHnQ1vUNsGvSdDd7Xd

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
