### ISSUE TITLE
Do not have Girl Avatar in Profile .

### ISSUE THREAD

**Issue by ishatripathi10** [nutbox-dao/nutbox-interface-v2#224]
I'm a girl and nutbox site do not have Girl avatar.
![bug](https://user-images.githubusercontent.com/44101272/152636762-46d70c22-74df-46ef-b930-c73db245d8d6.PNG)

Binance Smart Chain Address - 0xec844e2F4636DE2f8ae013f8A88B68fa44797666

**Comment by terryyyyyy** [comment]
Thank you for your feed back. We will add the avatars later.

**Comment by terryyyyyy** [comment]
Have added.
