### ISSUE TITLE
Explorer  not find transaction hash

### ISSUE THREAD

**Issue by Prem0240** [nutbox-dao/nutbox-interface-v2#245]
when i went to explorer there i entered my contract address but i didn't get my transaction you can see it in the image below

![IMG-20220205-WA0002](https://user-images.githubusercontent.com/99075469/152639643-feba9267-220b-4a0b-8b9b-4aabe8b93a76.jpg)

Solve this problem as soon as possible thank you

Trx address- TCvFNLXug4372kMtPa79XiKPFGQbg5tUtV

**Comment by terryyyyyy** [comment]
#168
