### ISSUE TITLE
WebSite Lag

### ISSUE THREAD

**Issue by GowdaGagan07** [nutbox-dao/nutbox-interface-v2#30]
Website slightly lags while connecting and while visiting staking/blog etc... And sometimes staking/blog and other options dont work properly we must tap 2-3 times on them and then it opens.. Hope u fix it 
Thank u 

TS6EZk1PemgR1NWvnE4C977NuLBjpxXgCL

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
