### ISSUE TITLE
Error in providing Liquidity pool

### ISSUE THREAD

**Issue by jmhub91** [nutbox-dao/nutbox-interface-v2#311]
While doing liquidity task everything got perfect confirmation to supply all well but it always shows liquidity is pending. I'm try 100 of times now I'm getting tired of this thing. Please resolve it

**Comment by terryyyyyy** [comment]
Yes, there's some issue on moonbase-alpha network. We have feed back the issue to the team.But this only on moonbase-network. It will be ok when we publish the official version.
