### ISSUE TITLE
fill wallet

### ISSUE THREAD

**Issue by FajarHikmatulloh** [nutbox-dao/nutbox-interface-v2#319]
I have a coin after creating a coin name with the amount I specified in the nutbox, and on the blockchain there is also, but when I want to stake "Total amount" 0, wait a few hours and then it appears

**Comment by FajarHikmatulloh** [comment]
also for the total coins with metamask not the same

![Screenshot (613)](https://user-images.githubusercontent.com/89757419/154132151-3aff352e-7c68-4bd3-9af7-f197f0fd3a5a.png)

**Comment by FajarHikmatulloh** [comment]
the same as other coins have been created by showing 0 amount
![Screenshot (614)](https://user-images.githubusercontent.com/89757419/154132471-f820dc91-652c-4d2b-b03e-c740de650533.png)

**Comment by FajarHikmatulloh** [comment]
when withdrawing the staking result is successful with a very good metamask popup speed, but there is a problem that the total drawn is not in accordance with the harvest staking display

**Comment by terryyyyyy** [comment]
Hi, the total amount on the card is showing the staked token amount, not the token total supply.
