### ISSUE TITLE
Create Community Deploy Error

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#32]
Fill in Start Block and make Stop Block to 10 years later or something and mint amout 1000 and then Add -> Deploy gives me this Contract error.
![y](https://user-images.githubusercontent.com/3170452/148832745-5666e4fc-a867-47f6-a8ff-a72b66f2bfb6.png)

**Comment by terryyyyyy** [comment]
That because the first block you set has past.You must set first block bigger than current block.I'll and the tips.
