### ISSUE TITLE
<Bug brief>

### ISSUE THREAD

**Issue by Bayu5677** [nutbox-dao/nutbox-interface-v2#320]
<Bug details> I have failed several times when I upload the C-TOKEN LOGO image
![Screenshot_2022-02-17-14-21-35-273_com miui gallery](https://user-images.githubusercontent.com/59202600/154425909-84b818bb-b5ff-4bb8-b507-abe53937b30a.jpg)

i found 404 PAGE NOT FOUND when i clicked the stripe button 3 above then clicked the home button
![Screenshot_2022-02-17-14-24-33-012_com yandex browser beta](https://user-images.githubusercontent.com/59202600/154426210-a9c0c297-022e-4c65-a923-ad9b16c2427d.jpg)

0x5F9a37E18307884fDd811a7cFe4C30D7F9E03C4E

**Comment by terryyyyyy** [comment]
What btn did you click to get the 404 page?

**Comment by Bayu5677** [comment]
In btn home sir

**Comment by Bayu5677** [comment]
![IMG_20220217_174606](https://user-images.githubusercontent.com/59202600/154459986-f019c17c-cdf3-4b6a-bb64-8fdacab2ba4b.jpg)
In Button home

**Comment by terryyyyyy** [comment]
Click this btn then shows 404?
Can you try again to check that?

**Comment by Bayu5677** [comment]
Same broo ,i cant send video,dm my twitter @Bayseo_ i give you video

**Comment by Bayu5677** [comment]
[](https://twitter.com/Bayseo_?t=ZJzG3TDPBITVLoWYcOhqVg&s=08) 
Dm for watch video

**Comment by Bayu5677** [comment]
Done

**Comment by terryyyyyy** [comment]
I haven't receive your e-mail.

**Comment by Bayu5677** [comment]
Cek again from bay29ahmad

**Comment by Bayu5677** [comment]
https://drive.google.com/file/d/1GoWyBZMx3yOllj9JGdxsVgfZv8a8SfUr/view?usp=drivesdk


Cek link my google drive,video im upload in here

Pada tanggal Rab, 23 Feb 2022 13.13, wangxi ***@***.***>
menulis:
