### ISSUE TITLE
Invalid view of the cursor 

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#324]
Invalid view of the cursor when attaching the logo and covers.
in css 
`cursor:default`
need replace on:
`cursor:pointer`
<img width="527" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/6646888/154849782-b91a3a82-adc8-4490-b499-51a0a75a3956.png">

**Comment by terryyyyyy** [comment]
It's ok now.
