### ISSUE TITLE
Invalid choice of restrictions for field validation 

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#325]
As limit on the length, the number of characters should be made, and not words. Words can be of different lengths. The user can print huge text simply without spaces. And the system takes it. 
<img width="471" alt="The community description cannot exceed 32" src="https://user-images.githubusercontent.com/6646888/154849908-ca5c4b13-594c-4763-8c74-28dca1fbab89.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/6646888/154850033-30e62502-e0bf-4583-8651-55ec8aa74fb4.png">

**Comment by terryyyyyy** [comment]
Yes, I will fix this one.
