### ISSUE TITLE
Routing error. Missed 404 page. 

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#326]
Every Website needs a 404 page if the URL does not exist or the URL might have been changed. 
With incorrectly entered addresses, we obtain code 200. Address processing is only after "# /". All that before him returns the main
But when the page is withdrawing https://test.nutbox.io/#/error-404 mechanics are incorrect. There should be no redirect - the address must be saved. The user must be provided with error information and solution options: return back, home, profile, and so on. The response code must be 404.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/6646888/154854017-b2d18186-e6d2-41d2-921e-38843ed63b62.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/6646888/154854127-1688a0c5-8270-4a04-98c9-de729b87cd8c.png">

**Comment by terryyyyyy** [comment]
Ok, I will add it.
