### ISSUE TITLE
Head optimization is absent 

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#328]
Same titles and meta tags on pages. There is no markup Open Graph on the site.
Meta tags & "og:" is important when placing links in social networks and messengers. 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6646888/154854511-b84171a9-6437-4cfe-8dcc-ffbd65e74042.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/6646888/154854530-a09ebbac-b730-4006-9002-0ea98b396d8b.png">

**Comment by terryyyyyy** [comment]
Have fixed.
