### ISSUE TITLE
创建社区资产Bug

### ISSUE THREAD

**Issue by abcallen** [nutbox-dao/nutbox-interface-v2#329]
在测试过程中，通过Walnut创建社区资产后，到设置社区资产分发策略，但由于刷新了一下网页，一切从头开始，但问题来了，社区资产应该已经创建，但goerli.etherscan.io找不到社区资产对应的合约地址。

参与测试地址：0x86E23F6BdC300F0414bc18005996353BD1585a0a
创建的社区资产名称：Nutboxiso
创建的社区资产符号：NSO
创建的社区资产发行量：6,600,000,000

这个问题有待解决。

**Comment by terryyyyyy** [comment]
Actually, this did not deploy a token on blockchain, that can be seen that you didn't sign anything with your wallet.
