### ISSUE TITLE
"Add Pool" missing ratio component

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#33]
Click "Add Pool" and try to add staking for BSC Steem and Hive but nothing shows up inside the create new pool
![image](https://user-images.githubusercontent.com/3170452/148840116-a98cebf9-3378-4d07-b2b0-6e36d564986f.png)
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/3170452/148840362-27d2c515-fe51-4db5-b40a-d6d81fad0890.gif)

OK won't work 
![image](https://user-images.githubusercontent.com/3170452/148840700-95e768da-23a5-487d-a3f5-8ddf59d6037b.png)

**Comment by terryyyyyy** [comment]
It's Ok now.Please check it.
