### ISSUE TITLE
Duplicated social icons after social info updated

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#34]
![image](https://user-images.githubusercontent.com/3170452/148841135-90004b7c-67f0-4444-8238-f8679f3bf24f.png)

Also the social info needs some sort of error check before update.
![image](https://user-images.githubusercontent.com/3170452/148841547-df262ff5-8457-40fa-9d2d-10a72e3d1f83.png)
This twitter link will go to https://test.nutbox.io/@yuzuT#/
and other links are all weird

**Comment by stakingdao** [comment]
Will fix this.

**Comment by terryyyyyy** [comment]
fixed.
