### ISSUE TITLE
Community Fund ratio unknown error

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#35]
Manage community page -> Asset -> click update and type in percentage and Confirm gets this error
![image](https://user-images.githubusercontent.com/3170452/148841917-490b1344-bcc1-4fc9-aa16-0106dd30df9f.png)

**Comment by stakingdao** [comment]
We have fix this issue.

**Comment by terryyyyyy** [comment]
fixed.
