### ISSUE TITLE
Nutbox home scrolling problem

### ISSUE THREAD

**Issue by ayushbishtcode** [nutbox-dao/nutbox-interface-v2#37]
Link community to web3.0 dialog box scrolling down is not working fine and i am not able to click Explore communities button in iphone . Interface is also not seen properly . Hope nutbox team will solve the problem asap 🙂
![D778323E-6C3E-46FC-9915-81DB67153230](https://user-images.githubusercontent.com/90823529/148926827-5c6560e0-d998-42f6-a8c9-92b3b83f4eb6.png)

BSC address-0x814713ad02cFCAB77f6D27A23d28D755387f5b49

**Comment by ayushbishtcode** [comment]
Image behind Web 3.0 text should be right also for proper UI .

**Comment by terryyyyyy** [comment]
We havn't adaptation phone UI so far.
