### ISSUE TITLE
Duplicated Social icons

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#38]
this looks like just an icon issue
![image](https://user-images.githubusercontent.com/3170452/148968747-b9e6f80b-70bb-4087-8624-a023e3856f0d.png)
one icon goes to github
the other goes to facebook but the same icon

but still it needs some kind of validation 
![image](https://user-images.githubusercontent.com/3170452/148969132-feca5e43-e41e-42e3-aaea-7267c0d19112.png)

**Comment by stakingdao** [comment]
Yes, we will add some check.

**Comment by terryyyyyy** [comment]
fixed.
