### ISSUE TITLE
Contract invocation error

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#39]
sum of ratio is 100% but error message shows up
![image](https://user-images.githubusercontent.com/3170452/148970068-63f0558c-dbaa-41c9-b903-02a77d50d900.png)

when create a new pool same error shows up too
![image](https://user-images.githubusercontent.com/3170452/148971140-dc1d2490-23ee-40e5-96e6-23990ba8e3fd.png)
![image](https://user-images.githubusercontent.com/3170452/148971370-318cbc3e-8500-4385-a617-c1dd7dfa5775.png)

**Comment by stakingdao** [comment]
We have fixed this issue.

**Comment by terryyyyyy** [comment]
fixed.
