### ISSUE TITLE
3 types of contract invocation error 

### ISSUE THREAD

**Issue by baecode** [nutbox-dao/nutbox-interface-v2#41]
Community name : Etarbucks
Community Balance : 500,000 ETH
Issuer's Metamask address : 0xd6F3d7FDB639f86eea83051435F1b9BC799348f1
Bug description : Popping up 'Contract invocation error' sign before progress

[Situations & Pictures]
1. In case of creating new pool
 
![777](https://user-images.githubusercontent.com/70386610/149316409-dab3be81-dd91-4efb-b0ec-0f7471443368.jpg)

2. In case of configuring pool ratio

![666](https://user-images.githubusercontent.com/70386610/149316455-6f65cf57-579b-44c6-a9eb-40d76295fb9e.jpg)

3. In case of delegating asset(Staking)

![555](https://user-images.githubusercontent.com/70386610/149316537-1360010c-3cd4-4503-991b-e3cf9fe137a6.jpg)

**Comment by stakingdao** [comment]
This is because the community balance is insuffient for the operations of community.The transfer of ctoken failed.
We just cancel community fund address for non-mintable community.

**Comment by alexbelij** [comment]
Add liquidity.
https://nutbox-io.gitbook.io/nutbox/using-nutbox/for-community/configure-staking-based-bootstrap-module
no?
