### ISSUE TITLE
side scroller problem in laptop

### ISSUE THREAD

**Issue by ayushbishtcode** [nutbox-dao/nutbox-interface-v2#42]
side scroller option is not showing in windows ,not able to go through the bottom of the test.nutbox.io webpage in my laptop (windows).
[](
![image](https://user-images.githubusercontent.com/90823529/149334365-1ddcc71d-9c21-411b-82cf-35962b5023ca.png)
)

**Comment by ayushbishtcode** [comment]
![image](https://user-images.githubusercontent.com/90823529/149334487-6ab9e5d6-a816-46f7-b0a6-d88361de1f49.png)

Binance smart chain address - 0x814713ad02cFCAB77f6D27A23d28D755387f5b49

**Comment by terryyyyyy** [comment]
Can't you use roller to scroll?
