### ISSUE TITLE
Spelling error 

### ISSUE THREAD

**Issue by ayushbishtcode** [nutbox-dao/nutbox-interface-v2#44]
there is a spelling error in the uploading community . 
Correct spelling is **upload**
![IMG-85734](https://user-images.githubusercontent.com/90823529/149546053-240bd98b-7cf0-4674-89d0-fcdcbf9b2287.jpg)

Bsc address -0x814713ad02cFCAB77f6D27A23d28D755387f5b49

**Comment by stakingdao** [comment]
Yes, these is a typo.Thank you for your feedback.

**Comment by terryyyyyy** [comment]
Yes, fixed this issue.

**Comment by ayushbishtcode** [comment]
Binance Chain Address -0x814713ad02cFCAB77f6D27A23d28D755387f5b49

**Comment by ayushbishtcode** [comment]
> Yes, fixed this issue.
Binance Chain Address -0x814713ad02cFCAB77f6D27A23d28D755387f5b49 @terryyyyyy
