### ISSUE TITLE
CRUD ( Create, Read, Update, dan Delete )

### ISSUE THREAD

**Issue by FajarHikmatulloh** [nutbox-dao/nutbox-interface-v2#45]
I'm starting to understand that after going back and forth from various features there is still a lot that needs to be added to make it more perfect to run in order for the tesnet to work better when used by participants, every time I perform an action or various button clicks it can't be recovered or reset but it happens automatically permanent, what about after I generate token but want to delete or edit because there are some errors that need to be added it doesn't seem to be fixed? and when i want to create new token or new contract this user can't do it either

**Comment by stakingdao** [comment]
Yes, this is on blockchain.You cannt delete contract on blockchain once it deployed on blockchain.

**Comment by terryyyyyy** [comment]
Can you descript details of these issues.

**Comment by FajarHikmatulloh** [comment]
Sir it's simple, let me explain, after successful execution, website related responses take a very long time to change, leaving users wondering if it worked or something failed to add, and every button or execution that becomes permanent must be notified first such as notifications and a little description explanation

**Comment by terryyyyyy** [comment]
Yes, the transaction on blockchain need long time to confirm.Some of our execution need to wait the finish of last operation.So these ops need user wait.But some of the ops no needs user to wait.User can do other ops after exceute these ops.And the result of these op will show when the result come out.

**Comment by FajarHikmatulloh** [comment]
when the user waits for the operation to run on the blockchain, it would be
nice if the button that remains on needs to be turned off so that when the
blockchain execution is complete, the button turns on again👍
thank you very much sir, hopefully continuous improvement will improve the
NUT operating system and the team will be given health🙏

Pada tanggal Sen, 24 Jan 2022 pukul 15.46 wangxi ***@***.***>
menulis:

**Comment by FajarHikmatulloh** [comment]
my addres BSC sir

0xF0E4f911cE4Ca27e9e53804442BEd1aB9EE4D454
