### ISSUE TITLE
Execution is successful but not working

### ISSUE THREAD

**Issue by FajarHikmatulloh** [nutbox-dao/nutbox-interface-v2#47]
there is still a lot that needs to be fixed by the dev, after today's update did not provide a complete fix, I've added a Steem Hive pool and with a success notification but when reloading the site page all pools are gone, only the bsc pool is left

and I did the addition of the pool again, the notification message failed

![Screenshot (407)](https://user-images.githubusercontent.com/89757419/149611229-77a37f59-4fcf-434e-9a5f-01d7e5def1e7.png)
![Screenshot (406)](https://user-images.githubusercontent.com/89757419/149611205-c2ab62be-6691-475b-ab00-c3065244c2ef.png)
![Screenshot (405)](https://user-images.githubusercontent.com/89757419/149611206-19db1d8d-3082-4e30-9ed7-56881e8b0dcf.png)

**Comment by stakingdao** [comment]
Thank you for your feed back.We found it cause by Thegraph update data so slowly.We are connecting with The graph team to solve this issue.

**Comment by terryyyyyy** [comment]
Yes, it's the graph update issue.We are connecting to The graph team to solve these questions.
