### ISSUE TITLE
Different smart contract for Ethereum token

### ISSUE THREAD

**Issue by safiq54** [nutbox-dao/nutbox-interface-v2#50]
Community name : Ethereum's Army
Issuer's Address : 0x9cf8650D5F6B678454f35999510Ce6EF5c08145A
Can't harvest for Ethereum token at staking platform reason : different smart contract between nutbox site & pancakeswap
![Screenshot_20220117-024444_Kiwi Browser](https://user-images.githubusercontent.com/36409512/149675449-873703f1-926c-4b32-940f-0ced9090676b.jpg)
![Screenshot_20220117-024352_Kiwi Browser](https://user-images.githubusercontent.com/36409512/149675451-d316b25f-694c-4efa-8465-883450ae79d9.jpg)
![Screenshot_20220117-023512_Kiwi Browser](https://user-images.githubusercontent.com/36409512/149675452-613744f3-78b1-4bd4-8433-1264ecab0b20.jpg)
![Screenshot_20220117-025826_Kiwi Browser](https://user-images.githubusercontent.com/36409512/149675869-03700840-209e-4058-b837-6de19eca23e2.jpg)

**Comment by terryyyyyy** [comment]
Yes, this is our test ETH token.That created for your test convenient.
