### ISSUE TITLE
Commuity I made was disappeared. Also staking pool I made were disappeared

### ISSUE THREAD

**Issue by cancerdoctor** [nutbox-dao/nutbox-interface-v2#51]
![image](https://user-images.githubusercontent.com/37767161/149737137-676041ad-4e47-44ee-8af9-c11c3ba20d1b.png)
I made a community and got a link: https://test.nutbox.io/#/sub-community/home/0x00514D1e
But the community was disappeared.
Also, when I made the community, I made a staking pool with STEEM delegation pool and CAKE staking pool.
I already checked it was completed, but there's no staking pool when I checked again.

**Comment by alexbelij** [comment]
I met such an error. sometimes the data is not loaded immediately.
