### ISSUE TITLE
Content not included

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#53]
Layout error. The content does not fit, there is no scrolling.

MacBook Pro (Retina, 13-inch, Early 2015), macOS Motnerey v12.1
Browser: Brave v1.34.80 Chromium: 97.0.4692.71 (x86_64)
2560 × 1600

<img width="1280" alt="Снимок экрана 2022-01-19 в 04 01 21" src="https://user-images.githubusercontent.com/6646888/150045771-c5fd2b10-4b77-499d-9f54-9c3181b50189.png">

**Comment by terryyyyyy** [comment]
fixed.

**Comment by alexbelij** [comment]
I cleared the cache and checked - no scrolling
![image](https://user-images.githubusercontent.com/6646888/150435810-cd526d2d-be1a-4c81-aa9e-df27952f9dda.png)
![image](https://user-images.githubusercontent.com/6646888/150436014-63dd4de9-76ca-4075-9b53-e184181ada37.png)
i see:
`overflow:hidden!important;`
override this block rule:
![image](https://user-images.githubusercontent.com/6646888/150436148-5b14bb5d-a64d-4f20-bc61-0c5a6c3ba43f.png)

**Comment by terryyyyyy** [comment]
Sorry, It's update now.
