### ISSUE TITLE
Icon not should be styled with cursor:pointer

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#55]
CSS error.
Icon not should be styled with cursor:pointer. Or the icon should be added to the link
https://test.nutbox.io/#/sub-community/home/?id=0xc5712e020be401129a89babc71414d77A9908592
![image](https://user-images.githubusercontent.com/6646888/150140732-c2809a9b-3542-4961-8577-5ed48e1371d7.png)

**Comment by terryyyyyy** [comment]
fixed.
