### ISSUE TITLE
Duplication of information

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#56]
In the community sidebar.
Pop-up notifications duplicate the specified text. They do not carry any semantic load. It would be more logical to display Transaction Hash and Вate.
![image](https://user-images.githubusercontent.com/6646888/150141132-b356d4f8-f611-4f3a-99f0-516ad2fb4997.png)

**Comment by terryyyyyy** [comment]
Click will goto transaction detail page.Here shows the tip is to show the whole info of this op.Some op info is too long to show.

**Comment by alexbelij** [comment]
I know it. But it's not about that. The point is in the senseless duplication of information with the help of pop-up windows. They don't make any sense. At all. These are redundant interface elements.

**Comment by alexbelij** [comment]
But now it displays the same information. There is no additional information available at the moment.
![image](https://user-images.githubusercontent.com/6646888/150826540-a3a5d7ae-81c4-4292-8c34-f8203d265120.png)
![image](https://user-images.githubusercontent.com/6646888/150826568-e7f8cb38-5fc7-4262-9275-01f18e35e0ed.png)
same text in popup. word by word. `Gutan007 deposit 1209.00 NUT to rise2022`
I just couldn't understand its purpose.
