### ISSUE TITLE
Governance: (Pass) Threshold min/max

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#57]
No minimum and maximum values. 
I have set the values for (Pass) Threshold 0,0000001. Saved. 
The displayed value has become 0.
And fields have no limits for max values.

https://test.nutbox.io/#/manage-community/vote

<img width="617" alt="Снимок экрана 2022-01-19 в 16 57 25" src="https://user-images.githubusercontent.com/6646888/150145328-0b338da9-0b43-4cb9-bfa0-3d66df1bd9b7.png">
<img width="711" alt="Снимок экрана 2022-01-19 в 17 01 06" src="https://user-images.githubusercontent.com/6646888/150145618-357f0972-312b-4906-8e70-bb07b748f4ee.png">
<img width="1070" alt="Снимок экрана 2022-01-19 в 16 56 32" src="https://user-images.githubusercontent.com/6646888/150145639-a86314cf-59ce-4590-b29a-dfff26f01096.png">

**Comment by terryyyyyy** [comment]
This value is depend on the specific community token.Depend on the supply of token.Surpose a ctoken total supply is 10, then community manager set the threhold to 0.00001 is ok.Other wise their is a token supply is 100000000000000000, and manager set it to 10000000 is ok.

**Comment by alexbelij** [comment]
10-30 characters. but there is no end. And for some reason both dots and commas are accepted in the input field. Saves everything correctly, but the banal input validation is broken. 
![image](https://user-images.githubusercontent.com/6646888/150441669-40695713-d05a-41f7-bc48-9374b7c0880d.png)
<img width="1280" alt="Снимок экрана 2022-01-21 в 03 07 32" src="https://user-images.githubusercontent.com/6646888/150441864-a9d4daf3-7583-4e76-9cd7-7f298fff1b58.png">
