### ISSUE TITLE
Start/Stop block picker

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#58]
When specifying blocks, the calculated date is displayed. But I can't select blocks via date picker.

<img width="639" alt="Снимок экрана 2022-01-19 в 17 05 19" src="https://user-images.githubusercontent.com/6646888/150146730-dec2b50a-5b5a-42bc-ae3f-05c934e4744a.png">

**Comment by terryyyyyy** [comment]
Yes, your advice is wanderfull. We will consider to do it.
