### ISSUE TITLE
Button not working / Missing click event

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#59]
Community => Member => Sidebar
The button with the text "Administrator" has the css attribute "cursor: pointer;", it is active, but it does not have any events. The event is missing or there must be another html-element (span,label..)
![image](https://user-images.githubusercontent.com/6646888/150148070-a386271c-89a8-4c32-9d93-b69865b02624.png)

**Comment by terryyyyyy** [comment]
fixed.
