### ISSUE TITLE
[Bug Bounty] In the setting your asset distribution, the Reward Amount is entered even if it is not a number.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#6]
**Bug Description :** 
In the setting your asset distribution, the Reward Amount is entered even if it is not a number.
And deploy submit error. 

**Path :** 
main > community (click) > create your community (click) > get started (click)

**Case / Action / Input data :** 
1.  input reward amount = 'abcd'
![image](https://user-images.githubusercontent.com/37989388/131277643-009e1085-258f-4d95-a64b-124ec14b6d02.png)

2. saved NaN(Not a Number)
![image](https://user-images.githubusercontent.com/37989388/131277874-25ec3831-457e-4262-8ee1-d7137f1da01b.png)

3. click deploy button
![image](https://user-images.githubusercontent.com/37989388/131277953-f8c94424-dc7b-40f7-b889-f1d315898308.png)

4. error
![image](https://user-images.githubusercontent.com/37989388/131277968-5eba3eee-cef5-4143-9f7a-e0392670319c.png)

**My Tron Wallet Address :** 
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Thank you for your feedback.We will improve this.

**Comment by terryyyyyy** [comment]
We have solved this issue.And send your bug bounty.Please close this issue.
