### ISSUE TITLE
Incorrect use of delimiters

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#61]
As a separator in the screenshot below, different characters are used for the same number ("," , ".").
Confuse.
For the integer part, either use a comma or a dot in any notation.
<img width="643" alt="Снимок экрана 2022-01-19 в 19 15 39" src="https://user-images.githubusercontent.com/6646888/150170864-93e4aabd-3819-446a-b3a7-49af5dc9bf4c.png">

**Comment by terryyyyyy** [comment]
How did you fill in this.I can't fill ',' in this input.

**Comment by alexbelij** [comment]
Browser: Brave v1.34.80 Chromium: 97.0.4692.71 (x86_64)
![tvKhA47JUO](https://user-images.githubusercontent.com/6646888/150442829-30a992ae-066a-47fe-a258-a552fb9330a7.gif)
