### ISSUE TITLE
balance reminders

### ISSUE THREAD

**Issue by AlvinKopin** [nutbox-dao/nutbox-interface-v2#64]
there are no restrictions on entering numbers/wallet balance reminders. I think this can be fixed

Email : alfienbrian@gmail.com
Addres : 0x44fB416439Fb115b34C2bA63bCC1F96caE36B41a

**Comment by alexbelij** [comment]
everything is working. how to repeat?

**Comment by terryyyyyy** [comment]
We just not validate the input of user. That depend on what they input.
