### ISSUE TITLE
Popup closing error

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#68]
An active pop-up window is closed by clicking on the cross or using ESC button on the keyboard.
Clicking outside the popup does not close it.
If you click outside the pop-up window and then click ESC, it will not close. It loses focus, so now you can close it only by clicking on the cross.
The pop-up window must either be closed by clicks outside its area, or by ESC always.
![QK8eH6FSKX](https://user-images.githubusercontent.com/6646888/150444143-bb22fe59-fa1e-473d-849f-ecc647d1429d.gif)

**Comment by terryyyyyy** [comment]
Hi, I guess you are a developer.We are glad to invite you to commit pull request to this repo at v3-dev branch.As a contributor we would like send you more NUT for reward.
