### ISSUE TITLE
[Bug Bounty] In the setting your asset distribution, the Reward Amount is entered can't add it from the 7th time.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#7]
**Bug Description :**
1. If the block numbers are long, they overlap.
2. In the setting your asset distribution, the Reward Amount is entered can't add it from the 7th time.
If this is right, it would be nice to have an help message.

**Path :**
main > community (click) > create your community (click) > get started (click)

**Case / Action / Input data :**
1. Case1 : block numbers overlap
2. Case2 : enter 7th Reward Amount >> 'Confirm Add' Button doesn't enable.

![image](https://user-images.githubusercontent.com/37989388/131312527-bfed2f57-b760-4c4a-8195-15fd8b0f086c.png)

My Tron Wallet Address :
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Yes, this is what we designed.You can only have 6 distribtuion part.

**Comment by terryyyyyy** [comment]
I will add tip to help user know he can only set 6 distributions.
And do you have any advice for the overlapping block numbers?

**Comment by hodolbak** [comment]
thanks!
I hope my idea helps.

**case1 : used shot scale And mouse over**
![image](https://user-images.githubusercontent.com/37989388/131609409-e523c66c-fe6b-40ae-a130-82a6e2f33622.png)

**case2 : block nunmbers, reward amount, delete icon - change position**
![image](https://user-images.githubusercontent.com/37989388/131609437-4d79e057-8ff6-41fe-a51a-5f39b9a5f9be.png)

**Comment by terryyyyyy** [comment]
> thanks!
> I hope my idea helps.
> 
> **case1 : used shot scale And mouse over**
> ![image](https://user-images.githubusercontent.com/37989388/131609409-e523c66c-fe6b-40ae-a130-82a6e2f33622.png)
> 
> **case2 : block nunmbers, reward amount, delete icon - change position**
> ![image](https://user-images.githubusercontent.com/37989388/131609437-4d79e057-8ff6-41fe-a51a-5f39b9a5f9be.png)

Good suggest,  I'll take one.
