### ISSUE TITLE
Bug for nutbox testnet

### ISSUE THREAD

**Issue by Dracays142** [nutbox-dao/nutbox-interface-v2#70]
<img width="809" alt="150445170-c7a47f0a-b8e0-4fe5-9923-0a330fecb2c5" src="https://user-images.githubusercontent.com/86523057/150625024-fbcbdc8c-b904-472b-b624-bd061a6bca5d.png">
Sidebar takes up a lot of space on mobile. Transfer it to the top in the form of a strip with a burger.
Similarly, the block with the search field. It's huge.
The community screen turns page into a longread.
Page zoom not working
The page loads completely. This causes lag. I would make an infinite scroll in the community directory, and for the image I would add lazy loading. In the default image quality, you can specify the svg inserted in the body of the page

Your team doesn't like boundary values, which causes a lot of problems.
I created a proposal with one space character in the title.
And why not make the whole block clickable.. not just the specified area?
An example on the contrary with overflow. we immediately see that the text field does not have scrolling and the property of hiding content
https://test.nutbox.io/#/sub-community/governance/detail/_z0CRSumzxVuE2_yMp8pj?id=0x1238b900a9FFdA7338759D3B1cF374E3f5696293

TRON ADRESS

TTAW7ftoWq2MwUHLcey9SCbFbdrKqcExCD
<img width="1135" alt="150445102-b7d2a201-070f-454b-8f6a-48e7854e4051" src="https://user-images.githubusercontent.com/86523057/150625011-999e7ec9-f348-4c39-a76f-1ce8a4743817.png">
<img width="1186" alt="150445106-ac806b70-c087-4102-9aed-e87536c8d882" src="https://user-images.githubusercontent.com/86523057/150625023-a9f7666d-6084-48e3-8179-682435c214d4.png">

**Comment by alexbelij** [comment]
My issue =>
https://github.com/nutbox-dao/nutbox-interface-v2/issues/69
