### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by Dracays142** [nutbox-dao/nutbox-interface-v2#71]
In the community sidebar.
Pop-up notifications duplicate the specified text. They do not carry any semantic load. It would be more logical to display Transaction Hash and
![150141132-b356d4f8-f611-4f3a-99f0-516ad2fb4997](https://user-images.githubusercontent.com/86523057/150625118-f4fbc5f5-5266-4c1c-a50f-94dd957e6a2c.png)

Tron ADRESS
TTAW7ftoWq2MwUHLcey9SCbFbdrKqcExCD

**Comment by alexbelij** [comment]
are you serious? again copying my own screenshots and comments =>
https://github.com/nutbox-dao/nutbox-interface-v2/issues/56

ps: bro, and I also came from gleam
