### ISSUE TITLE
Community is not  creating

### ISSUE THREAD

**Issue by Dracays142** [nutbox-dao/nutbox-interface-v2#72]
After approving  it is stucked
![Screenshot_2022-01-24-20-30-24-990_com kiwibrowser browser](https://user-images.githubusercontent.com/86523057/150807748-223981a7-754a-47dd-96e7-93308ab93aa3.jpg)
![Uploading Screenshot_2022-01-24-20-30-17-486_com.kiwibrowser.browser.jpg…]()

**Comment by terryyyyyy** [comment]
What's the next status after you approve the community?
