### ISSUE TITLE
Content does not fit into the block

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#73]
Buttom "+ Create Proposal" does not fit into the block

MacBook Pro (Retina, 13-inch, Early 2015), macOS Motnerey v12.1
Browser: Brave v1.34.80 Chromium: 97.0.4692.71 (x86_64)
2560 × 1600

Link: https://test.nutbox.io/#/sub-community/governance?id=0x4adDD7C1a1c338f975b5cEB46b3617553E29488c
![image](https://user-images.githubusercontent.com/6646888/150834543-48512329-424a-4bb3-9615-e9ce923c728a.png)

Firefox 96.0.2 (64 бита): 
![image](https://user-images.githubusercontent.com/6646888/150838053-4c8662c0-1336-476c-adb3-e96d9358ac30.png)

Safari v15.2 (17612.3.6.1.6)
<img width="965" alt="Снимок экрана 2022-01-24 в 20 58 12" src="https://user-images.githubusercontent.com/6646888/150838154-fce1841a-cbb8-4729-a502-95665e16fb05.png">

**Comment by terryyyyyy** [comment]
Ok, we will fix it.
