### ISSUE TITLE
Community website field check

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#76]
Options I was able to save:
![image](https://user-images.githubusercontent.com/6646888/150844350-28c5e5cc-5b39-4c43-ba3a-a30abd990735.png)
<img width="1001" alt="Снимок экрана 2022-01-24 в 21 45 11" src="https://user-images.githubusercontent.com/6646888/150844632-f2c851fe-0f9b-42f8-af81-6f3967d15bbd.png">
<img width="997" alt="Снимок экрана 2022-01-24 в 21 46 44" src="https://user-images.githubusercontent.com/6646888/150844858-f1545128-f9cf-4a0b-9cfe-8d739c0f2e92.png">
<img width="993" alt="Снимок экрана 2022-01-24 в 22 03 21" src="https://user-images.githubusercontent.com/6646888/150847265-5ff4f3a3-f2ee-443d-8a7c-22a7b11acc5f.png">

**Comment by terryyyyyy** [comment]
This is depend on the manager.
