### ISSUE TITLE
Сommunity name and description input limits

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#77]
There are currently no restrictions on input fields. 
The corresponding notification is shown only when you try to save. 
Moreover, for a name, it is measured in words, not in symbols, which is not so logical.
It is more logical to set up to 80 characters for titles as in Google search results, and for descriptions from 160 to 290 (on average 160-180).
Name input:
`<input data-v-c5d23f38="" type="text" placeholder="Please input Community Name" class="form-control" id="__BVID__32">`
replaced by
`<input data-v-c5d23f38="" type="text" minlength="4" maxlength="80" placeholder="Please input Community Name" class="form-control" id="__BVID__32">`
<img width="356" alt="Снимок экрана 2022-01-24 в 21 16 27" src="https://user-images.githubusercontent.com/6646888/150841401-3c741a0c-380f-4e7b-9c75-6d9ff2078854.png">

I added over 9,000 words to the description field. Nothing told me that this was not possible. But when sending data, the server returned an error message.
Add label under the fields with information about restrictions. Mark the required fields.

**Comment by terryyyyyy** [comment]
Thanks for your advice.I'll take it.
