### ISSUE TITLE
Rename pool

### ISSUE THREAD

**Issue by alexbelij** [nutbox-dao/nutbox-interface-v2#78]
At the moment, the ability to change the Profit Sharing Ratio has been added, but you cannot change the names of the pools. I got a pool without a name.

<img width="856" alt="Снимок экрана 2022-01-24 в 22 15 13" src="https://user-images.githubusercontent.com/6646888/150848955-13b3ed49-ba6c-4abd-92b1-8a7dd8eda233.png">

**Comment by terryyyyyy** [comment]
I have make a validation of pool name input, I tested it user cant input null for name to create pool. How did you do that.
And the pool name cant be changed if it deployed to blockchain.

**Comment by alexbelij** [comment]
<img width="1016" alt="Снимок экрана 2022-02-10 в 15 55 17" src="https://user-images.githubusercontent.com/6646888/153412609-1a491ca5-9d64-4186-b4be-e99f246c8327.png">
I managed to repeat this only a few times with the window closing immediately after confirming the transaction in the wallet. the transaction goes through, the pool is created, but the name remains empty. means send the name early or block the close by displaying a notification

**Comment by terryyyyyy** [comment]
Ok, I know, will fix this next version.
