### ISSUE TITLE
stake in other communities

### ISSUE THREAD

**Issue by FajarHikmatulloh** [nutbox-dao/nutbox-interface-v2#79]
After I approved the Community Nutbox for staking and I refreshed several times, I still can't participate in staking in Community Nut as shown in the image below
![Screenshot (450)](https://user-images.githubusercontent.com/89757419/150888832-f5587079-2801-4d4d-a6d5-99c04dd20389.png)

**Comment by terryyyyyy** [comment]
There's something wrong, We will fix it soon.

**Comment by FajarHikmatulloh** [comment]
oky thanks you sir
