### ISSUE TITLE
[Bug Bounty] In the setting your asset distribution, If you delete it does not changed to the previous startblock datetime.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#8]
**Bug Description :**
In the setting your asset distribution, If you delete it does not changed to the previous startblock datetime.

**Path :**
main > community (click) > create your community (click) > get started (click)

**Case / Action / Input data :**
1. 'Confirm Add' Click
![image](https://user-images.githubusercontent.com/37989388/131314435-7d0ee7eb-c6d4-4b7c-89db-dee0e94e952a.png)
2. 'Delete Icon' Click
![image](https://user-images.githubusercontent.com/37989388/131314542-7eaf4ed5-5764-4c10-9380-c1dd6e514ce6.png)
3. it does not changed to the previous startblock datetime
![image](https://user-images.githubusercontent.com/37989388/131314621-82b3738a-1038-4689-b588-2b469a7b12c3.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
