### ISSUE TITLE
Connect Metamask Issue

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#80]
My metamask is using BSC Testnetwork and connected.
![image](https://user-images.githubusercontent.com/3170452/150889598-6623ae5c-cc19-4d43-9d51-9c27344009e6.png)

But still "Connect Metamask" button shows up so click this button to connect metamask again.
![image](https://user-images.githubusercontent.com/3170452/150889703-6993c3e2-94d1-4057-8c3e-caa31649a54f.png)

And then, it wants to connect to Moonbase alpha
![image](https://user-images.githubusercontent.com/3170452/150889743-b3250b7d-9072-44ca-adbc-41e513377a5e.png)

Are we using moobase or BSC testnet? or the button is connecting to a wrong network.

**Comment by terryyyyyy** [comment]
#81
