### ISSUE TITLE
Testnet Token Issue and tutorial update.

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#81]
I did TEST NUT and TEST Moonbase token.
![image](https://user-images.githubusercontent.com/3170452/150889980-cbce6b88-da71-4409-88d2-4779b7bb941d.png)
But they don't show up in metamask if I use BSC testnet.

If I change the network to Moonbase, they both show up.
![image](https://user-images.githubusercontent.com/3170452/150890095-928afce3-dee4-4d14-85cc-2264f49dd8aa.png)

But again, is this the right network? The tutorial said I should use BSC testnet.

This whole tutorial needs to be updated for beta test 3.

**Comment by terryyyyyy** [comment]
Sorry about that, we have change to moonbase network when the 3rd round test begin.
