### ISSUE TITLE
Creating proposal has been pending

### ISSUE THREAD

**Issue by baecode** [nutbox-dao/nutbox-interface-v2#88]
Governance Threshold : 100,000 ctoken

![image](https://user-images.githubusercontent.com/70386610/151023957-1968cd7a-26d1-4870-8232-1b000fe4616d.png)

![image](https://user-images.githubusercontent.com/70386610/151024233-8ffbb043-c5f2-44bd-a8c8-146ac4d0e7d9.png)

Community member still can not participate governance, showing up 'wait',  even though community have fund more than threshold.

**Comment by terryyyyyy** [comment]
This 'wait' means the proposal havent started.That depends on what startblock you set when created the proposal .You can check in the propsal detals, there shows the start date.
