### ISSUE TITLE
My Proposal/ Governance does not appear in public

### ISSUE THREAD

**Issue by PanjiHikaru27** [nutbox-dao/nutbox-interface-v2#89]
I've been created my proposal but does not appear in public
![IMG_20220126_012912_165](https://user-images.githubusercontent.com/53354481/151037160-b6325444-0b1b-41ca-ac07-ca0650212fd8.jpg)

**Comment by terryyyyyy** [comment]
Hi, when you configuared the proposal system the proposal module can be seen in sub-community page.And the proposals need to you create at the second pic you send,
