### ISSUE TITLE
[Bug Bounty] In the setting your asset distribution, the Block Number is entered even if it is not a number.

### ISSUE THREAD

**Issue by hodolbak** [nutbox-dao/nutbox-interface-v2#9]
**Bug Description :**
In the setting your asset distribution, the Block Number is entered even if it is not a number.
And deploy submit error.

**Path :**
main > community (click) > create your community (click) > get started (click)

**Case / Action / Input data :**
1. input start block = '5410822abcd', input stop block = '6000000abcd'
![image](https://user-images.githubusercontent.com/37989388/131352199-2c50756c-dc93-4d5d-852f-d9fc294173e8.png)
2. saved start / stop block NaN, input stop block = 'abcdeg', input reward amount = 'abcdeg'
![image](https://user-images.githubusercontent.com/37989388/131352477-71fceaf3-3181-4713-9da8-96388931fc52.png)
3. saved start / stop block NaN, click deploy button
![image](https://user-images.githubusercontent.com/37989388/131352767-85c613c7-17c1-4f12-a0e1-7392a9658a7d.png)
4. error
![image](https://user-images.githubusercontent.com/37989388/131352871-49cc7559-ef08-4e7f-b9aa-e851e0001234.png)

**My Tron Wallet Address :**
TQtuaRMmCDFwGGX4yHcQMEwe7DHC743qjg

**Comment by terryyyyyy** [comment]
Have fixed it

**Comment by terryyyyyy** [comment]
Closed.Change to test new version.
