### ISSUE TITLE
Approve pool option in Nutbox Stake NUT is not responding.

### ISSUE THREAD

**Issue by ayushbishtcode** [nutbox-dao/nutbox-interface-v2#90]
![approve pool issue](https://user-images.githubusercontent.com/90823529/151043533-85745c84-3b58-48e3-bd90-92ca63145007.PNG)

Even After deducting Dev Fee in official **NUTBOX Staking pool** i am not able to stake my nut token in particular pool.

**Comment by terryyyyyy** [comment]
We have fixed this issue.
