### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/nutbox-interface-v2#95]
Something weird about the validation.

Facebook: facebbok.com redirect to https://test.nutbox.io/facebbok.com#/
![image](https://user-images.githubusercontent.com/3170452/151206385-bd879420-14bf-46ed-bf56-34e948c9609d.png)

And https://twitter.com this is not a URL but https://twitter.com/ this is okay?

**Comment by terryyyyyy** [comment]
Will fix this.
