### ISSUE TITLE
Error when uploading Community logo

### ISSUE THREAD

**Issue by xiangstan** [nutbox-dao/nutbox-interface-v2#98]
Error message: 

> Pictures fail to upload, Please try again

Console shows:

> POST https://v2-api-test.nutbox.io/qiNiu/upload 419
> VM812:1

Browser: Brave
OS: Windows 11

Cannot create a community without logo.

**Comment by terryyyyyy** [comment]
There maybe some error with 3rd part tool of image upload.
We will check it again.
